name = "Daisy"
description = "Theme for a project portfolio (based on Tailwind CSS)."
license = "MIT"
homepage = "https://github.com/awinterstein/zola-theme-daisy"
min_version = "0.9.0"                                                  # The minimum version of Zola required
demo = "https://zola-daisy.winterstein.biz"                            # Live demo URL

[author]
name = "Adrian Winterstein"
homepage = "https://www.winterstein.biz"

[markdown]
# Whether to do syntax highlighting
# Theme can be customized by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
# Switches for optional features
enable_theme_switching = false

daisyui_theme_light = "winterstein-light"
daisyui_theme_dark = "winterstein-dark"

footer_notice = ""

[extra.social]
codeberg = ""
github = ""
gitlab = ""
stackoverflow = ""
mastodon = ""
linkedin = ""
instagram = ""
youtube = ""
signal = ""
telegram = ""
email = ""
phone = ""
